ai_assistance_general: https://chat.deepseek.com/share/9bipslzunwd20ly38v
ai_assistance_image_magik_1: https://chat.deepseek.com/share/keze1qzhjuwchyzolc # Closed
ai_assistance_image_magik_2: https://chat.deepseek.com/share/kewy1rkmikpnk71php
github_repo: https://github.com/febr3s/post_generator.git
main_github_commits: https://github.com/febr3s/post_generator/commits/main/
blog: https://febr3s.github.io/100DH